name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"

    name: "PHP ${{ matrix.php }}"

    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          tools: composer

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.20.2"

      - name: Install dependencies
        run: composer update

      - name: Install JS dependencies
        run: npm install

      - name: Run tests
        run: cd test && ../vendor/bin/run_unit_tests

# vim:ts=2:sw=2:et
